### PR TITLE
Italian Localization

### PR DESCRIPTION
**Pull request by ZeroKun265**
Italian is not gender neutral as english so i'll have to remake the translation once i see them in game, i am not  mod developer so i can't figure out where in the code and therefore the game they are used, not all of them at least.

### CODE REVIEW

**Comment by Nosrick** [comment]
Gah, sorry!
I completely missed this, and really appreciate you taking the time to make this translation.

I'll check this out, run my game in Italian and post some screenshots here for you, so you can refine things as you please. Are there any particular phrases you're worried about?

Give me a few days though, haha.

**Comment by ZeroKun265** [comment]
Great, i don't think there will be too much to change, maybe if in some parts you build text out of multiple translations (like if you were to make "rabbit" + "stew" it wouldn't make sense in Italian because it would need to be "stew of rabbit" literally) but again, i think it'll be fine. Also take your time don't worry

**Comment by Nosrick** [comment]
Just to confirm; are you happy with me including the translation as it is currently?

I did go looking at your it_it.json, and it seems like you've managed to work around the issue you mentioned by doing "Stufato di %s", which would insert the ingredients _after_ the noun.

I've kind of been off the modding recently, but I'm hoping to pick things back up with the release of 1.19.1. Thanks again for the contribution.

**Comment by ZeroKun265** [comment]
Yes, they are good to be inserted, also don't worry about the time, i ended up learning how to make mods actually, and built this and checked, it's all good, you can add it in

**Comment by Nosrick** [comment]
Perfect, thank you so much! It'll be included in the next release.

**Pull request merged**
