### PR TITLE
Russian and Ukrainian translation

### PR DESCRIPTION
**Pull request by DMHYT**

### CODE REVIEW

**Comment by Nosrick** [comment]
Thank you so much for this!

**Comment by Nosrick** [comment]
Oh, I actually forgot to say: the 1.18.2 branch is the latest version. I'll merge 1.18.2 into main and see how it affects the translation.

Would you be able to update it? I'm sure I've added options since then.

**Comment by DMHYT** [comment]
I see only 3 new keys in 1.18.2 branch, and it's OK. You can merge, and I'll send another pull there.

**Comment by Nosrick** [comment]
There we go, `main` is now up to date with 1.18.2. The `1.18.1` branch also includes the new lang keys, but I can just port over whatever updates you do to that.

**Pull request merged**
